# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '产线UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(933, 176)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 21, 18, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(36, 21, 114, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(156, 21, 16, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(174, 21, 114, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(300, 20, 591, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_50 = QtWidgets.QLabel(self.splitter)
        self.label_50.setObjectName("label_50")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_49 = QtWidgets.QLabel(self.splitter)
        self.label_49.setObjectName("label_49")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(11, 91, 80, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(97, 91, 24, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(139, 92, 133, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 60, 80, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(11, 120, 80, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(97, 120, 78, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(181, 121, 133, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 60, 80, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(10, 150, 244, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_6.raise_()
        self.lineEdit_6.raise_()
        self.splitter.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "mac"))
        self.lineEdit.setText(_translate("Form", "F4-8E-38-87-01-C9"))
        self.label_6.setText(_translate("Form", "ip"))
        self.lineEdit_6.setText(_translate("Form", "192.168.251.72"))
        self.label_7.setText(_translate("Form", "port"))
        self.lineEdit_7.setText(_translate("Form", "9001"))
        self.label_50.setText(_translate("Form", "产线："))
        self.lineEdit_50.setText(_translate("Form", "01"))
        self.label_49.setText(_translate("Form", "工站"))
        self.lineEdit_49.setText(_translate("Form", "00"))
        self.label_2.setText(_translate("Form", "注册结果"))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.pushButton.setText(_translate("Form", "断开连接"))
        self.pushButton_3.setText(_translate("Form", "发送RFID扫码"))
        self.label_4.setText(_translate("Form", "rfid"))
        self.lineEdit_4.setText(_translate("Form", "010203005060708"))
        self.pushButton_5.setText(_translate("Form", "发送推杆信号"))
        self.pushButton_4.setText(_translate("Form", "发送气缸压力"))
        self.label_9.setText(_translate("Form", "Pressure Warn"))
        self.lineEdit_9.setText(_translate("Form", "0"))
        self.pushButton_6.setText(_translate("Form", "发送心跳检测"))
        self.pushButton_7.setText(_translate("Form", "异常警告"))
        self.label_3.setText(_translate("Form", "故障码"))

