# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '工站UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 430)
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 350, 80, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 320, 80, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(100, 319, 84, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(190, 320, 111, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(10, 110, 521, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(self.splitter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.splitter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_13 = QtWidgets.QLabel(self.splitter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(10, 50, 751, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_43 = QtWidgets.QLabel(self.splitter_2)
        self.label_43.setObjectName("label_43")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_51 = QtWidgets.QLabel(self.splitter_2)
        self.label_51.setObjectName("label_51")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.label_15 = QtWidgets.QLabel(self.splitter_2)
        self.label_15.setObjectName("label_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(36, 21, 114, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 21, 18, 16))
        self.label.setObjectName("label")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(174, 21, 114, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(156, 21, 16, 16))
        self.label_6.setObjectName("label_6")
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(294, 20, 621, 23))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_7 = QtWidgets.QLabel(self.splitter_4)
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_50 = QtWidgets.QLabel(self.splitter_4)
        self.label_50.setObjectName("label_50")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_49 = QtWidgets.QLabel(self.splitter_4)
        self.label_49.setObjectName("label_49")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_19 = QtWidgets.QLabel(self.splitter_4)
        self.label_19.setObjectName("label_19")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton.setObjectName("pushButton")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(10, 140, 521, 23))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_14 = QtWidgets.QLabel(self.splitter_3)
        self.label_14.setObjectName("label_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_12 = QtWidgets.QLabel(self.splitter_3)
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_17 = QtWidgets.QLabel(self.splitter_3)
        self.label_17.setObjectName("label_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.splitter_5 = QtWidgets.QSplitter(Form)
        self.splitter_5.setGeometry(QtCore.QRect(10, 80, 791, 23))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_23 = QtWidgets.QLabel(self.splitter_5)
        self.label_23.setObjectName("label_23")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_16 = QtWidgets.QLabel(self.splitter_5)
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_9 = QtWidgets.QLabel(self.splitter_5)
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.splitter_6 = QtWidgets.QSplitter(Form)
        self.splitter_6.setGeometry(QtCore.QRect(10, 290, 297, 23))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_18 = QtWidgets.QLabel(self.splitter_6)
        self.label_18.setObjectName("label_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.splitter_6)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.splitter_7 = QtWidgets.QSplitter(Form)
        self.splitter_7.setGeometry(QtCore.QRect(10, 261, 231, 23))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.splitter_7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_32 = QtWidgets.QLabel(self.splitter_7)
        self.label_32.setObjectName("label_32")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.splitter_8 = QtWidgets.QSplitter(Form)
        self.splitter_8.setGeometry(QtCore.QRect(11, 231, 232, 23))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.splitter_8)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_39 = QtWidgets.QLabel(self.splitter_8)
        self.label_39.setObjectName("label_39")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.splitter_8)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.splitter_9 = QtWidgets.QSplitter(Form)
        self.splitter_9.setGeometry(QtCore.QRect(10, 200, 232, 23))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.splitter_9)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_36 = QtWidgets.QLabel(self.splitter_9)
        self.label_36.setObjectName("label_36")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.splitter_9)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.splitter_10 = QtWidgets.QSplitter(Form)
        self.splitter_10.setGeometry(QtCore.QRect(10, 380, 244, 23))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter_10)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_21 = QtWidgets.QLabel(self.splitter_10)
        self.label_21.setObjectName("label_21")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.splitter_10)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(740, 390, 54, 12))
        self.label_22.setObjectName("label_22")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(800, 390, 101, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(741, 303, 24, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(771, 303, 133, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(741, 332, 24, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(771, 332, 133, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(741, 361, 24, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(771, 361, 133, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(771, 274, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(741, 274, 24, 16))
        self.label_2.setObjectName("label_2")
        self.splitter_11 = QtWidgets.QSplitter(Form)
        self.splitter_11.setGeometry(QtCore.QRect(11, 172, 413, 23))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.splitter_11)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_26 = QtWidgets.QLabel(self.splitter_11)
        self.label_26.setObjectName("label_26")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.splitter_11)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_8 = QtWidgets.QLabel(self.splitter_11)
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.splitter_11)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.splitter_11.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        self.lineEdit_4.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_2.raise_()
        self.label_2.raise_()
        self.splitter_10.raise_()
        self.splitter_8.raise_()
        self.splitter_9.raise_()
        self.pushButton_14.raise_()
        self.pushButton_11.raise_()
        self.label_20.raise_()
        self.lineEdit_20.raise_()
        self.splitter.raise_()
        self.splitter_2.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.lineEdit_6.raise_()
        self.label_6.raise_()
        self.splitter_4.raise_()
        self.splitter_3.raise_()
        self.splitter_5.raise_()
        self.splitter_6.raise_()
        self.splitter_7.raise_()
        self.label_22.raise_()
        self.lineEdit_22.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_14.setText(_translate("Form", "生产工序申请"))
        self.pushButton_11.setText(_translate("Form", "生产订单申请"))
        self.label_20.setText(_translate("Form", "orderbatchcode"))
        self.lineEdit_20.setText(_translate("Form", "20190409002001"))
        self.pushButton_4.setText(_translate("Form", "员工上机"))
        self.label_10.setText(_translate("Form", "type"))
        self.lineEdit_10.setText(_translate("Form", "01"))
        self.label_11.setText(_translate("Form", "staffcode"))
        self.lineEdit_11.setText(_translate("Form", "60000001"))
        self.label_13.setText(_translate("Form", "上机结果"))
        self.pushButton_12.setText(_translate("Form", "衣架返工申请"))
        self.label_43.setText(_translate("Form", "rfid"))
        self.lineEdit_42.setText(_translate("Form", "A000000000000001"))
        self.label_51.setText(_translate("Form", "返工工序"))
        self.lineEdit_51.setText(_translate("Form", "001"))
        self.label_15.setText(_translate("Form", "返工申请结果"))
        self.lineEdit.setText(_translate("Form", "F4-8E-38-87-01-03"))
        self.label.setText(_translate("Form", "mac"))
        self.lineEdit_6.setText(_translate("Form", "192.168.251.72"))
        self.label_6.setText(_translate("Form", "ip"))
        self.label_7.setText(_translate("Form", "port"))
        self.lineEdit_7.setText(_translate("Form", "9001"))
        self.label_50.setText(_translate("Form", "产线："))
        self.lineEdit_50.setText(_translate("Form", "01"))
        self.label_49.setText(_translate("Form", "工站"))
        self.lineEdit_49.setText(_translate("Form", "01"))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.label_19.setText(_translate("Form", "注册结果"))
        self.pushButton.setText(_translate("Form", "断开连接"))
        self.pushButton_5.setText(_translate("Form", "员工下机"))
        self.label_14.setText(_translate("Form", "type"))
        self.lineEdit_13.setText(_translate("Form", "01"))
        self.label_12.setText(_translate("Form", "staffcode"))
        self.lineEdit_12.setText(_translate("Form", "60000001"))
        self.label_17.setText(_translate("Form", "上机结果"))
        self.pushButton_13.setText(_translate("Form", "RFID衣架绑定"))
        self.label_23.setText(_translate("Form", "rfid"))
        self.lineEdit_23.setText(_translate("Form", "A000000000000001"))
        self.label_16.setText(_translate("Form", "barcode"))
        self.lineEdit_16.setText(_translate("Form", "00000000000000000000000000"))
        self.label_9.setText(_translate("Form", "衣架绑定结果"))
        self.pushButton_6.setText(_translate("Form", "生产批次确认"))
        self.label_18.setText(_translate("Form", "orderbatchcode"))
        self.lineEdit_17.setText(_translate("Form", "20190413001001"))
        self.pushButton_10.setText(_translate("Form", "出站完成"))
        self.label_32.setText(_translate("Form", "rfid"))
        self.lineEdit_30.setText(_translate("Form", "A000000000000001"))
        self.pushButton_9.setText(_translate("Form", "出站申请"))
        self.label_39.setText(_translate("Form", "rfid"))
        self.lineEdit_38.setText(_translate("Form", "A000000000000001"))
        self.pushButton_8.setText(_translate("Form", "进站完成"))
        self.label_36.setText(_translate("Form", "rfid"))
        self.lineEdit_35.setText(_translate("Form", "A000000000000001"))
        self.pushButton_3.setText(_translate("Form", "异常警告"))
        self.label_21.setText(_translate("Form", "故障码"))
        self.label_22.setText(_translate("Form", "在站数量"))
        self.label_3.setText(_translate("Form", "员工"))
        self.label_4.setText(_translate("Form", "工序"))
        self.label_5.setText(_translate("Form", "产量"))
        self.label_2.setText(_translate("Form", "站号"))
        self.pushButton_7.setText(_translate("Form", "进站申请"))
        self.label_26.setText(_translate("Form", "rfid"))
        self.lineEdit_26.setText(_translate("Form", "A000000000000001"))
        self.label_8.setText(_translate("Form", "申请结果"))

